# Required to avoid a linker error on Windows when building the dylib.
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[alias]
run-wasm = "run --release --package run-wasm -- --package wgpu-hot-reload"
